services:
  db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW  
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Project9@123
      MYSQL_PASSWORD: Project9@123
      MYSQL_DATABASE: nextcloud   
      MYSQL_USER: cloudadmin
    
  app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always  
    ports:
      - 8080:80
  
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      MYSQL_PASSWORD: Project9@123
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: cloudadmin
      MYSQL_HOST: db    
        
  nginx:
    image: nginx:latest
    container_name: nextcloud-nginx
    restart: always
    ports:
      -  "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nextcloud:/var/www/html:ro    

  




